/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import java.awt.Color;
import java.awt.Graphics;
import java.util.HashSet;

/**
 *
 * @author riley
 */
public class Magic8BallGUI extends javax.swing.JFrame {

    /**
     * Creates new form Magic8BallGUI
     */
    String answer = "Hello";
    
    public Magic8BallGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        askQuestionLabel = new javax.swing.JLabel();
        askQuestionInputTextField = new javax.swing.JTextField();
        questionSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magic8BallGUI");
        setPreferredSize(new java.awt.Dimension(500, 625));

        askQuestionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        askQuestionLabel.setText("Ask Your Question:");

        askQuestionInputTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        askQuestionInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askQuestionInputTextFieldActionPerformed(evt);
            }
        });

        questionSubmitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        questionSubmitButton.setText("Shake the 8-Ball");
        questionSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(askQuestionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(askQuestionInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(questionSubmitButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(askQuestionLabel)
                    .addComponent(askQuestionInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionSubmitButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void askQuestionInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askQuestionInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_askQuestionInputTextFieldActionPerformed

    private void questionSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionSubmitButtonActionPerformed
        
        String submittedQuestion = askQuestionInputTextField.getText();
        answer = Magic8Ball.askQuestion(submittedQuestion);
        System.out.println(answer);
        repaint();
        
    }//GEN-LAST:event_questionSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Magic8BallGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Magic8BallGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Magic8BallGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Magic8BallGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Magic8BallGUI().setVisible(true);
            }
        });
    }
    
    public void paint(Graphics g)
    {
        super.paint(g);
        
        g.setColor(Color.BLACK);
        g.fillOval(30, 50, 440, 440);
        
        g.setColor(Color.WHITE);
        g.fillOval(150, 170, 200, 200);
        
        g.setColor(Color.RED);
        g.drawString(answer, 175, 265);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField askQuestionInputTextField;
    private javax.swing.JLabel askQuestionLabel;
    private javax.swing.JButton questionSubmitButton;
    // End of variables declaration//GEN-END:variables
}
