/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import java.util.Random;

/**
 *
 * @author riley
 */
public class NumberGuess extends javax.swing.JFrame {

    /**
     * Creates new form NumberGuess
     */
    
    private Random rand = new Random();
    private int secretNumber = rand.nextInt(101) + 1;
        
    public NumberGuess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberGuessInstructionsLabel = new javax.swing.JLabel();
        numberGuessTextField = new javax.swing.JTextField();
        numberGuessSubmitButton = new javax.swing.JButton();
        numberGuessNewSecretNumberButton = new javax.swing.JButton();
        numberGuessPreviousResultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NumberGuess");

        numberGuessInstructionsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numberGuessInstructionsLabel.setText("Enter a guess:");

        numberGuessTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        numberGuessSubmitButton.setText("Submit Guess");
        numberGuessSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberGuessSubmitButtonActionPerformed(evt);
            }
        });

        numberGuessNewSecretNumberButton.setText("New Number");
        numberGuessNewSecretNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberGuessNewSecretNumberButtonActionPerformed(evt);
            }
        });

        numberGuessPreviousResultLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberGuessPreviousResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberGuessInstructionsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numberGuessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberGuessSubmitButton)
                    .addComponent(numberGuessNewSecretNumberButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberGuessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberGuessInstructionsLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberGuessSubmitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numberGuessNewSecretNumberButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(numberGuessPreviousResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberGuessSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberGuessSubmitButtonActionPerformed
        
        String guessNumber = numberGuessTextField.getText();
        int guessNumberFormatted = Integer.parseInt(guessNumber);
        
        if(guessNumberFormatted > secretNumber)
        {
            numberGuessPreviousResultLabel.setText("too high");
        }
        else if(guessNumberFormatted < secretNumber)
        {
            numberGuessPreviousResultLabel.setText("too low");
        }
        else if(guessNumberFormatted == secretNumber)
        {
            numberGuessPreviousResultLabel.setText("correct");
        }
        
    }//GEN-LAST:event_numberGuessSubmitButtonActionPerformed

    private void numberGuessNewSecretNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberGuessNewSecretNumberButtonActionPerformed
        
        secretNumber = rand.nextInt(101) + 1;
        
    }//GEN-LAST:event_numberGuessNewSecretNumberButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberGuess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel numberGuessInstructionsLabel;
    private javax.swing.JButton numberGuessNewSecretNumberButton;
    private javax.swing.JLabel numberGuessPreviousResultLabel;
    private javax.swing.JButton numberGuessSubmitButton;
    private javax.swing.JTextField numberGuessTextField;
    // End of variables declaration//GEN-END:variables
}
