/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import java.text.NumberFormat;

/**
 *
 * @author riley
 */
public class TipCalculator extends javax.swing.JFrame {

    /**
     * Creates new form TipCalculator
     */
    public TipCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billDollarDisplayLabel = new javax.swing.JLabel();
        billDollarTextField = new javax.swing.JTextField();
        tip10PercentButton = new javax.swing.JButton();
        tip15PercentButton = new javax.swing.JButton();
        tip20PercentButton = new javax.swing.JButton();
        tipDollarDisplayLabel = new javax.swing.JLabel();
        tipAmountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TipCalculator");

        billDollarDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billDollarDisplayLabel.setText("Bill Amount:");

        billDollarTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billDollarTextField.setText("Enter Bill Here");
        billDollarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billDollarTextFieldActionPerformed(evt);
            }
        });

        tip10PercentButton.setText("10% Tip");
        tip10PercentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tip10PercentButtonActionPerformed(evt);
            }
        });

        tip15PercentButton.setText("15% Tip");
        tip15PercentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tip15PercentButtonActionPerformed(evt);
            }
        });

        tip20PercentButton.setText("20% Tip");
        tip20PercentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tip20PercentButtonActionPerformed(evt);
            }
        });

        tipDollarDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tipDollarDisplayLabel.setText("Tip Amount:");

        tipAmountLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(billDollarDisplayLabel)
                        .addGap(32, 32, 32)
                        .addComponent(billDollarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tipDollarDisplayLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(tip10PercentButton)
                        .addGap(48, 48, 48)
                        .addComponent(tip15PercentButton)
                        .addGap(48, 48, 48)
                        .addComponent(tip20PercentButton)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tipAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billDollarDisplayLabel)
                    .addComponent(billDollarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip10PercentButton)
                    .addComponent(tip15PercentButton)
                    .addComponent(tip20PercentButton))
                .addGap(57, 57, 57)
                .addComponent(tipDollarDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tip10PercentButton.getAccessibleContext().setAccessibleName("10% Tip Button");
        tip10PercentButton.getAccessibleContext().setAccessibleDescription("10% Tip Button");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billDollarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billDollarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billDollarTextFieldActionPerformed

    private void tip20PercentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tip20PercentButtonActionPerformed
        String billTotal = billDollarTextField.getText();
        double tipTotal = Double.parseDouble(billTotal) * .2;
        NumberFormat tipFormat = NumberFormat.getCurrencyInstance();
        String tipTotalFormat = tipFormat.format(tipTotal);
        tipAmountLabel.setText(tipTotalFormat);
    }//GEN-LAST:event_tip20PercentButtonActionPerformed

    private void tip10PercentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tip10PercentButtonActionPerformed
        String billTotal = billDollarTextField.getText();
        double tipTotal = Double.parseDouble(billTotal) * .1;
        NumberFormat tipFormat = NumberFormat.getCurrencyInstance();
        String tipTotalFormat = tipFormat.format(tipTotal);
        tipAmountLabel.setText(tipTotalFormat);
    }//GEN-LAST:event_tip10PercentButtonActionPerformed

    private void tip15PercentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tip15PercentButtonActionPerformed
        String billTotal = billDollarTextField.getText();
        double tipTotal = Double.parseDouble(billTotal) * .15;
        NumberFormat tipFormat = NumberFormat.getCurrencyInstance();
        String tipTotalFormat = tipFormat.format(tipTotal);
        tipAmountLabel.setText(tipTotalFormat);
    }//GEN-LAST:event_tip15PercentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billDollarDisplayLabel;
    private javax.swing.JTextField billDollarTextField;
    private javax.swing.JButton tip10PercentButton;
    private javax.swing.JButton tip15PercentButton;
    private javax.swing.JButton tip20PercentButton;
    private javax.swing.JLabel tipAmountLabel;
    private javax.swing.JLabel tipDollarDisplayLabel;
    // End of variables declaration//GEN-END:variables
}
